spring.application.name=SpringIAPromptDemo
server.port=${SERVER_PORT:8080}

# For production LLama use 10.75.42.2:8000
#spring.ai.ollama.base-url=http://${OLLAMA_HOST_URL:localhost}:${OLLAMA_PORT:11434}/
spring.ai.ollama.base-url=http://10.75.42.2:8000
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:llama3.3}
spring.ai.ollama.chat.options.temperature=0
spring.ai.ollama.init.pull-model-strategy=when_missing

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.jackson.serialization.fail-on-empty-beans=false
#logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

output.file.directory=${OUTPUT_DIRECTORY:src/main/resources/output-data/}
input.graph.directory=${GRAPH_DIRECTORY:src/main/resources/input-data/graphs/}
input.file.path=${METADATA_FILE:src/main/resources/input-data/metadata.csv}
